version: "3"

services:
  spring-java:
    container_name: spring-sample-container
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "..:/myapp:cached"
    tty: true